### ISSUE TITLE
wget not found

### ISSUE THREAD

**Issue by greybeard-code** [cowboysdude/MMM-Astrology#14]
Fresh install for first time and getting a black screen and an error. 
Running Raspbian GNU/Linux 10 (buster). MagicMirror 2.15

[02.05.2021 13:25.01.412] [ERROR] App threw an error during load
[02.05.2021 13:25.01.414] [ERROR] Error: Cannot find module 'wget'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)

**Comment by greybeard-code** [comment]
Just saw this version is no longer supported.

Also. commenting out the wget require in node_helper.js worked

**Comment by cowboysdude** [comment]
Awesome :)  Great job!  Thank you!  Glad you got it working.....
