### ISSUE TITLE
Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by blackc2004** [cowboysdude/MMM-Astrology#9]
After installing this I get the error:

```
Error: Cannot find module 'xml2js'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js:40:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'xml2js'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Astrology/node_helper.js:40:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
```

**Comment by cowboysdude** [comment]
Completely delete the directory and restart. 
Follow the readme as you only need to do a git clone......  NO package.json as it's not needed because request is already in the mirror so no need to reinstall it :)
